# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Github Portal"
author:
  name: Uwe Eichkorn
  email: hanswiaheiri@gmail.com
copyright: © 2021
description: >- # this means to ignore newlines until "baseurl:"
  The portal page of my private but public repositories. The repositories contain various programs, apps, services etc. written in C#, Javascript...
baseurl: "" # the subpath of your site, e.g. /blog
url: "uwe-e.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Uwe Eichkorn

globalstrings:
  readmore: Read more

# generate social links in footer
social_links:
    github:  https://github.com/uwe-e
    xing: https://www.xing.com/profile/Uwe_Eichkorn
    codeproject: https://www.codeproject.com/Members/Uwe-Eichkorn

repositories:
  bsetunes_xamarin: https://github.com/uwe-e/BSE.Tunes.Xamarin

collections:
  - tunes_xamarin

# Build settings
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-coffeescript

  # Specify the output style
sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
